# Generated by Django 5.1.6 on 2025-02-24 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('company', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('body_style', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to='images/')),
                ('image', models.ImageField(upload_to='images/')),
                ('mileage', models.TextField(max_length=100)),
                ('hp', models.TextField(max_length=100)),
                ('type', models.TextField(max_length=100)),
            ],
        ),
    ]
